### ISSUE TITLE
Proxy services solution research

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#101]
## Nginx proxy Manager

cockpit:  url:9090
nginxproxy: url:9001  or localhost:9001

Add a package for Cockpit for request the login page of nginxproxymanager 

path:

* /usr/share/cockpit
* /ect/cockpit/cockpit.conf

- alias 访问：nginxproxymanager, cockpit
- cockpit 菜单 iframe: http 访问 cockpit 方可生效，但cockpit会自动跳转到 https

通过common安装cockpit后，插件情况：
centos: 容器有 navigator无
ubutnu:  容器无 navigator无

文件管理安装参考：https://github.com/45Drives/cockpit-navigator

**Comment by chendelin1982** [comment]
* alias 访问：nginxproxymanager, cockpit
* cockpit 菜单 iframe:  http 访问 cockpit 方可生效，但cockpit会自动跳转到 https

**Comment by qiaofeng1227** [comment]
centos:

**Comment by chendelin1982** [comment]
* [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy): automatic service discovery for Nginx
* [traefik](https://doc.traefik.io/traefik/)

**Comment by qiaofeng1227** [comment]
决定采用nginxproxymanange，不用traefik
