### ISSUE TITLE
task [ Check chrony status] failed!

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/websoft9#106]
linux with GNOME / Xfce on Ubuntu 20.04 on AWS
  
TASK [role_os : Check chrony status] *******************************************
fatal: [54.157.211.208]: FAILED! => {"changed": true, "cmd": "systemctl restart chronyd", "delta": "0:00:00.019310", "end": "2022-04-13 08:21:42.561580", "msg": "non-zero return code", "rc": 5, "start": "2022-04-13 08:21:42.542270", "stderr": "Failed to restart chronyd.service: Unit chronyd.service not found.", "stderr_lines": ["Failed to restart chronyd.service: Unit chronyd.service not found."], "stdout": "", "stdout_lines": []}
  
![WP~_TW5%6PYDG3ZJJTLFYR9](https://user-images.githubusercontent.com/54173243/163133431-a37d3848-039d-48fd-94ee-013756248036.png)

**Comment by qiaofeng1227** [comment]
重新再stackhub下生产
