### ISSUE TITLE
select python IDE

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#114]
1. [offical research](https://www.jetbrains.com/lp/python-developers-survey-2020)
2. autopep8 vs yapf vs black（code rule-auto checking）

**Comment by chendelin1982** [comment]
选型条件
* 规范有落地的软件或插件（必要）
* 代码和注释的可读性
* 消除冗余代码
* 模板化

**Comment by qiaofeng1227** [comment]
PyCharm Community
