### ISSUE TITLE
appmanage send commands to Host server

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#137]
**What type of your feature request?**  

- [ ] Build docker image
- [ ] [Connect ](https://docs.docker.com/engine/reference/commandline/context_use/) Host（宿主机）Docker Server
- [ ] run/send commands to host server

**Comment by qiaofeng1227** [comment]
[pipe方案](https://stackoverflow.com/questions/32163955/how-to-run-shell-script-on-host-from-docker-container)

**Comment by chendelin1982** [comment]
经过讨论，采用客户端+服务端代理的模式。可选方案：

* cockpit 代理服务
* [Fabric](https://docs.fabfile.org/en/stable/)

**Comment by zhaojing1987** [comment]
通用方案：https://segmentfault.com/a/1190000042002239
