### ISSUE TITLE
Docker and linux/windows image on Windows

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#15]
**What type of your feature request?**  

- [ ] WSL for Windows Server
- [ ]  linux image running on WSL

**Comment by chendelin1982** [comment]
refer to:
1. https://dev.to/davidkou/running-docker-in-windows-subsystem-for-linux-wsl2-1k43
2. https://www.endpointdev.com/blog/2020/06/linux-development-in-windows-10-docker-wsl-2/
3. AWS have provided Microsoft Windows Server 2016 Base with Containers - ami-08fc2fd2cb93abd08
4. 阿里云 Windows 2019 with containers
5. [RUN LINUX CONTAINER ON WINDOWS IN AZURE VM](https://netweblog.wordpress.com/2019/10/18/docker-linux-container-on-windows-in-azure-virtual-machine)

**Comment by chendelin1982** [comment]
Testing result
1. 阿里云 Windows 2019 with containers only support windows docker image
2. Windows container seem [not support GUI](https://docs.microsoft.com/zh-cn/virtualization/windowscontainers/quick-start/lift-shift-to-containers)
3. [Using Remote Desktop Services in Containers](https://withinrafael.com/2018/03/09/using-remote-desktop-services-in-containers/), this solution not test

**Comment by chendelin1982** [comment]
悬赏任务：
1. 开源众包：https://zb.oschina.net/project/detail.html?id=17494514

**Comment by qiaofeng1227** [comment]
windows每个版本对应特定的windows容器，容器没有可视化界面
