### ISSUE TITLE
appmanage action - pay ¥50

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#150]
1. https://github.com/Websoft9/StackHub//workflows)/appmanage_docker.yml
2. imagename :  websoft9dev/appmanage:dev

**Comment by zl-go** [comment]
action编写完毕，可正确上传镜像至dockerhub
文件链接为：https://github.com/Websoft9/StackHub/blob/main/.github/workflows/appmanage_docker.yml
其中镜像描述文字可在文件中自行修改
![image](https://user-images.githubusercontent.com/62973206/227432259-efe4e973-92a9-423a-8c30-7e424e4b9d37.png)
