### ISSUE TITLE
管理用户自启动docker compose 应用

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#152]
需求：  用户自行通过 docker compose 安装的应用需要通过 stackhub 进行管理，以便于用户可以通过统一视图管理应用，确保安全可用。

具体需求：可列出显示，可启停和删除

**Comment by chendelin1982** [comment]
后端实现方案：

1. 仅可以管理标准 docker compose up 的应用
2. 应用路径、环境变量文件、docker compose 文件名称统一反向推导
3. api 增加一个属性 official_app= true | false，判断标准：variables.json 存在以及其元数据4项存在[name,trademark,requirements.cup, requirements.memory], app 图标相对地址

**Comment by qiaofeng1227** [comment]
按照需求区分 用户自己安装的compose应用
