### ISSUE TITLE
SSH terminal received parameters

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#154]
**What type of your feature request?**  

- [x] received parameters from other Cockpit plugins
- [ ] URL

**Comment by zhaojing1987** [comment]
解决方案：将cockpit的ssh终端源码嵌入appstore项目中，作为一个组件，并修改源码使得支持参数的传入
1、在cockpit的GitHub项目中将https://github.com/cockpit-project/cockpit/tree/main/pkg/lib  目录下的：cockpit-components-context-menu.jsx 、cockpit-components-terminal.jsx、cockpit-dark-theme.js、cockpit-rsync-plugin.js、cockpit-po-plugin.js添加到项目中，(自定义放在src/lib文件夹下)
2、在create-react-app项目中加入cockpit库：
使用create-react-app创建的项目不支持手动修改配置，为加入cockpit插件，使用以下步骤：
2.1:在index.html 中 引入cockpit脚本 <script type="text/javascript" src="../base1/cockpit.js"></script>
2.2:安装react-app-rewired：作用是用来帮助重写react脚手架配置yarn add react-app-rewired customize-cra -D
2.3:配置(修改为)package.json的命令
     "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject"
   }
2.4:项目根目录下定义配置文件 config-overrides.js（重写配置：引入cockpit插件）
 const CockpitRsyncPlugin = require("./src/lib/cockpit-rsync-plugin");
const {
    override,
    addWebpackPlugin,
    addWebpackExternals,
} = require('customize-cra')
  
module.exports = override(
    addWebpackExternals({
        "cockpit": "cockpit"
      }),
    addWebpackPlugin(new CockpitRsyncPlugin()),
)
3、构建一个自己的terminal组件 ：terminal.js  修改相关原代码，使得可以接受参数
