### ISSUE TITLE
gitclone.sh 

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#164]
**What type of your feature request?**  

- [ ] 实现git clone 多网络通道，选择最优速度的地址
- [ ] 其他

**Comment by qiaofeng1227** [comment]
能够通过执行脚本，在任何有公网的服务器下载 github项目，能对速度进行判断，选择最优的地址进行clone

pip安装的参照方法：https://github.com/Websoft9/StackHub/blob/main/scripts/pipinstall.sh
