### ISSUE TITLE
AppDomainAdd need to support HTTPS proxy

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#171]
**What type of your feature request?**  

Some container need https access, so AppDomainAdd should support it

**Comment by qiaofeng1227** [comment]
requirement:
AppDomainAdd need to support HTTPS proxy

Modify estimation method:
api AppDomainAdd  add a parameter https_access(true or false)
manage.py function app_domain_add: Calling the nginxproxymanage API parameters also requires corresponding changes


Working hours: 2hour
