### ISSUE TITLE
更新logo图标 - pay ¥100

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#173]
将contenful的Base_Media对应url的图片，下载并覆盖到：https://github.com/Websoft9/StackHub//appmanage/static/images

[Base_Media](https://app.contentful.com/spaces/ffrhttfighww/content_types/media/fields)

https://libs.websoft9.com/Websoft9/logo/product/phpmyadmin-websoft9.png

**Comment by qiaofeng1227** [comment]
每天晚上12点进行一个aciton自动更新。写死条件是日期

**Comment by zl-go** [comment]
contentful中url错误：

1. custom-ibox（Stackhub中未同步）
2. kodcloud
