### ISSUE TITLE
非root账号无法安装StackHub  [StackHub]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#174]
**Describe the bug**

## 非root账号无法通过脚本安装StackHub
**curl https://websoft9.github.io/StackHub/install/install.sh | bash**

```
mkdir: cannot create directory ‘/data/apps’: Permission denied
fatal: could not create work tree dir '/data/library': Permission denied
Clone failed, retrying 1/5
fatal: could not create work tree dir '/data/library': Permission denied
Clone failed, retrying 2/5
fatal: could not create work tree dir '/data/library': Permission denied
Clone failed, retrying 3/5
fatal: could not create work tree dir '/data/library': Permission denied
Clone failed, retrying 4/5
fatal: could not create work tree dir '/data/library': Permission denied
Clone failed, retrying 5/5
fatal: could not create leading directories of '/data/apps/stackhub': Permission denied
Clone failed, retrying 1/5
fatal: could not create leading directories of '/data/apps/stackhub': Permission denied
Clone failed, retrying 2/5
fatal: could not create leading directories of '/data/apps/stackhub': Permission denied
Clone failed, retrying 3/5
fatal: could not create leading directories of '/data/apps/stackhub': Permission denied
Clone failed, retrying 4/5
fatal: could not create leading directories of '/data/apps/stackhub': Permission denied
Clone failed, retrying 5/5
fatal: could not create work tree dir '/data/stackhubweb': Permission denied
Clone failed, retrying 1/5
fatal: could not create work tree dir '/data/stackhubweb': Permission denied
Clone failed, retrying 2/5
fatal: could not create work tree dir '/data/stackhubweb': Permission denied
Clone failed, retrying 3/5
fatal: could not create work tree dir '/data/stackhubweb': Permission denied
Clone failed, retrying 4/5
fatal: could not create work tree dir '/data/stackhubweb': Permission denied
Clone failed, retrying 5/5
Parpare to install Cockpit ...
Reading package lists... Done
E: The value 'jammy-backports' is invalid for APT::Default-Release as such a release is not available in the sources
Cockpit allow root user
main: line 209: /etc/cockpit/disallowed-users: No such file or directory
Set cockpit port to 9000 ...
sed: can't read /lib/systemd/system/cockpit.socket: No such file or directory

```

基于上述结果，sudo su 提权后安装，异常
```
E: The value 'jammy-backports' is invalid for APT::Default-Release as such a release is not available in the sources
Cockpit allow root user
Set cockpit port to 9000 ...
```

## 直接 sudo su 提权后安装
**Cookpit 安装不成功**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] Ubuntu22.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
1. 非root加上强制处理，不切换到root脚本提示错误退出
2. 安装cockpit无法安装上，不是root或者ubuntu的问题，是因为腾讯云的系统有些源和其他云不一致，需要手动配置，更新包即可
