### ISSUE TITLE
Manifest overrides to change menu

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#191]
**What type of your feature request?**  

* Add new features](https://cockpit-project.org/guide/latest/packages.html#package-manifest)
![image](https://github.com/Websoft9/websoft9/assets/16741975/356212aa-e753-4f5e-8fb4-c17b4daa6304)

**Comment by qiaofeng1227** [comment]
在cockpit296版本，修改override可引起变化，但是只有一个顶级菜单的修改没有找到方法；（menu->tools）
在cockpit195版本，override覆盖无法引起菜单变化。
