### ISSUE TITLE
install.sh for websoft9

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#215]
##  UE
```
curl https://websoft9.github.io/install.sh | bash
```

完成100%

### 前置检查

* 80 端口作为 HTTP 端口，不能被占用
* cockpit 端口默认到 9000，不能被占用

完成100%

### 约束

* 权限：root 账户
* 操作系统支持：Debian10+, Ubuntu20+, Redhat7+, CentOS7+, OracleLinux7+，Fedora33+
* 架构：x86-64, ARM-64

完成100%

### 规范

* 安装路径：*/data/apps/Stackhub*  

完成100%

### 组件

* 系统安装：cockpit, docker, git, curl, wget,
* Docker 安装：nginxproxymanager, appmanager

完成100%

### URL 统一性

为了方便前端调用后端服务，URL 需要同域

完成100%

### Cockpit 插件

/usr/share/cockpit

#### 新增

* docker for all OS
* [cockpit-navigator](https://github.com/45Drives/cockpit-navigator)
* app store

完成100%

#### 删除

* 内核崩溃转储
* 应用程序
* selinux

完成100%（插件操作系统不兼容问题见其他issue）

### 异常

* 安装过程有异常，需给出精准的提示，并引导用户提交 Issue

完成100%

### 服务验证

* cockpit.socket
* cockpit

完成100%

**Comment by chendelin1982** [comment]
实现：

## 插件新增

将插件的 HTML 源码拷贝到 /usr/share/cockpit

**Comment by qiaofeng1227** [comment]
目前可以开启服务器一键安装 使用
