### ISSUE TITLE
install.sh support RockyLinux9/8

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#228]
**What type of your feature request?**  

- [Install docker on rockylinux](https://docs.rockylinux.org/gemstones/docker/)

- Rockylinux have install cockpit by default (有待进一步确认), but run InstallPlugins()  `sudo systemctl enable --now cockpit` 
error below and install exit

```
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled or disabled using systemctl.

Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
```

Solution(官方标准方案):  systemctl enable --now cockpit.socket

- Can not login Cockpit by root, solved it by: https://github.com/Websoft9/websoft9/issues/229

**Comment by chendelin1982** [comment]
Debian11/CentOS steam also have disallowed-users by default

**Comment by qiaofeng1227** [comment]
There is not docker install about Rocky Linux on docker official [documentation](https://docs.docker.com/engine/install/centos/),install by centos's flow

**Comment by qiaofeng1227** [comment]
delete shell about cockpit service
```
sudo systemctl daemon-reload
sudo systemctl enable --now cockpit.socket
#sudo systemctl enable --now cockpit
sudo systemctl restart cockpit.socket
#sudo systemctl restart cockpit
```
