### ISSUE TITLE
no file browser plugin at CentOS Stream 9,Rocky Linux9, RedHat 9

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#239]
**Describe the bug**

no file browser plugin at CentOS Stream 9
![image](https://github.com/Websoft9/websoft9/assets/16741975/f27b6f68-9618-484c-8957-39008e57bf4f)

**Comment by qiaofeng1227** [comment]
rl9 is not [supported](https://github.com/45Drives/cockpit-navigator)

**Comment by qiaofeng1227** [comment]
copy the  navigator plugin from rl8 or ubantu  also is failed

**Comment by qiaofeng1227** [comment]
websoft9 product a artifact.
