### ISSUE TITLE
安装结束后的更友好提示 [websoft9]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#253]
**What type of your feature request?**  

- [x] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

![image](https://github.com/Websoft9/websoft9/assets/62225175/2ed2645a-9543-4d2e-ae86-43a0f6220c77)

安装结束后，建议 输出：
1、appstore访问地址：http://ip:9000
2、输出账号密码

提示 使用 **w9 default** CLI命令获取上述信息

**Comment by qiaofeng1227** [comment]
cli 单独作为 大的需求完成，其他已经对应
