### ISSUE TITLE
docker compose db services repeat 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#269]
Phenomena: phpmyadmin can not login.

Reason:use phpmyadmin to connect db container, if container-name and installed  docker-compose's are same.

Edit method:
AppInstall api update:
appname can't use mysql, mariadb, postgres, mongodb.

show message(define constant):
The APP cannot use the following database keywords [mysql, mariadb, postgres, mongodb]!

**Comment by qiaofeng1227** [comment]
AppInstall api update:
appname can't use mysql, mariadb, postgres, mongodb.

show message:
The APP cannot use the following database keywords [mysql, mariadb, postgres, mongodb]!

**Comment by chendelin1982** [comment]
方案可能性：service 名称不允许连接？
