### ISSUE TITLE
application settings tabs page of Stackhub console

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#27]
**What type of your feature request?**  

application settings tabs page of Stackhub console, below tab is need

* index tab
* print logs tab
* resource tab: CPU, Memory

**Comment by zhaojing1987** [comment]
## Index Tab

frontend, backend 来源于 variables.json
APP_* 来源于 .env

前台地址：ip:APP_PORT/frontend
后台地址：ip:APP_PORT/backend

账号密码：APP_USER/APP_PASSWORD
