### ISSUE TITLE
AppInstall API update: add param domains[] 【3】

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#280]
**What type of your feature request?**  

- [x] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**

**Comment by qiaofeng1227** [comment]
## requirement

AppInstall API update: add param domains[]


## API

AppInstall

```
AppInstall(app_name, customer_app_name, app_version, domains[]){

ResponseData is not need to change.
}

```

manage.py

# new code below 460 line ( myLogger.info_logger... )

```
function  install_app_delay(app_name, customer_app_name, app_version, domains[]){
            ...
             

System_domain=read domain item from Websoft9 settings.conf

for (domain: domains)
  app_domain_add(app_id, domain)
  if domain is not the subdomain of System_domain
    set_domain(domain, app_id)
    break;
  else domains.length < 2
    set_domain(domain, app_id)
} 
```
add testunit of this function

**Comment by fatelei** [comment]
@qiaofeng1227  

```py
for (domain: domains)
  app_domain_add(app_id, domain)
  if domain is not the subdomain of System_domain
    set_domain(domain, app_id)
    break;
  else domains.length < 2
    set_domain(domain, app_id)
} 
```

in for cycle check domains length ？

in function `app_domain_add` 

if app proxy is None, it will exec `set_doamin(domain, app_id)`

![image](https://github.com/Websoft9/websoft9/assets/961094/b5fc2df7-c7d3-4460-bb79-40c4d36b2c3e)

@fatelei 

we will add new file nginx.py to rewrite api about nginx.
