### ISSUE TITLE
update, delete, and list system settings【2】

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#285]
## Requirement

When user access websoft9  first-time, show bind domain message in settings menu, user input domains and bind to the websoft9.

## Design

 * domain save into /usr/src/app/config/settings.conf
 * add util function update_settings(Dictionary)  and delete_settings(Dictionary) and list_settings()
```
funtion update_settings(Dictionary) {

if no [name=value], add them
if have [name=value], modify them
}


funtion delete_settings(Dictionary) {

if no [name=value], do nothing
if have [name=value], delete them
}

# list all  [name=value]
function list_settings()
{

return function

}
```

### AppListSettings
```
param: 
settings:Dictionary(json)

ResponseData: 
{
  settings: {
           "domain": "test.websoft9.com",
            "appstore_preview_update": true,
            ....
       }
}
Error：
{
  Code：xxx
  Message：xxx
  Detail：xxx
}
```

### AppUpdateSettings

```
param: 
settings:Dictionary(json)
ResponseData: 
{

}
Error：
{
  Code：xxx
  Message：xxx
  Detail：xxx
}
```

### AppDeleteSettings

```
param: 
settings:Dictionary(json)
ResponseData: 
{
}
Error：
{
  Code：xxx
  Message：xxx
  Detail：xxx
}
```

**Comment by fatelei** [comment]
this is domain related apis

<img width="794" alt="image" src="https://github.com/Websoft9/websoft9/assets/961094/e868a682-f6f2-4e26-8931-b907321ee474">

**Comment by fatelei** [comment]
config file can be ini format
