### ISSUE TITLE
optimize api docs experience

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#296]
**What type of your feature request?**  

We [set var for docs description](https://github.com/Websoft9/websoft9/blob/main/appmanage/api/v1/routers/apps.py) now, but it format is difficult to control.  These need to optimize

Docker use the same API framework with us, but it experience is very good: [Docker API docs](https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerCreate)

**Comment by zhaojing1987** [comment]
在定义API的Parameters和Responses时，建议使用SCHEMA，特别是响应时，为每个API定义“RESPONSE SCHEMA”（响应模型），然后为响应模型添加注释即可。
例如Nginx Proxy Manager API的SCHEMA：
![image](https://github.com/Websoft9/websoft9/assets/7624828/01841318-769f-40d7-b02d-7008b4530b41)

为复杂的输入参数定义模型：
![image](https://github.com/Websoft9/websoft9/assets/7624828/53dfc5e1-29e8-4659-af83-72b8a905ec69)
为响应定义模型：
![image](https://github.com/Websoft9/websoft9/assets/7624828/08803838-b749-4f1e-bf04-e586c3a14e3a)

例如，定义一个响应模型，并添加注释：
```
from pydantic import BaseModel, Field

class Item(BaseModel):
    name: str = Field(..., description="The name of the item")
    price: float = Field(..., description="The price of the item in USD")
    description: str = Field(None, description="The optional description of the item")
```

**Comment by mayo7e** [comment]
i will like to work on these, please. thanks

**Comment by qiaofeng1227** [comment]
@mayo7e thanks for follow our project. The websoft9 project structure has been restructured, and once the architecture is finalized, we can invite you to participate together

**Comment by mayo7e** [comment]
Okay. Thanks for responding.  Is there any timeline for this, just to know when I can reach out again

**Comment by chendelin1982** [comment]
> Okay. Thanks for responding. Is there any timeline for this, just to know when I can reach out again

The new version will publish at October, we will provide you email for me, that we can concact you directly

**Comment by mayo7e** [comment]
Ok that's great. Here is my email: mayowa.wh@gmail.com

**Comment by chendelin1982** [comment]
> Ok that's great. Here is my email: [mayowa.wh@gmail.com](mailto:mayowa.wh@gmail.com)

OK
