### ISSUE TITLE
Local installation, service does not work correctly [websoft9]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#298]
**Describe the bug**

After using the script to install locally, the local LAN IP address cannot be obtained and the related services cannot be started normally

![image](https://github.com/Websoft9/websoft9/assets/62225175/4e9d429d-9afd-4642-be40-6881348ff390)

![image](https://github.com/Websoft9/websoft9/assets/62225175/c1e8ea16-c190-43d3-b0a2-63421becae98)

The automatically obtained IP is the Internet IP, while the LAN IP is 192.168
![image](https://github.com/Websoft9/websoft9/assets/62225175/28f6e68f-5d73-42a6-be1d-f84db02443d6)

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [x] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] Ubuntu22.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by chendelin1982** [comment]
Nginx 配置文件已改为通配符 Solved
