### ISSUE TITLE
API AppList error

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#304]
**Describe the bug**

![image](https://github.com/Websoft9/websoft9/assets/16741975/4f71bdd5-89e5-44d7-9c90-67595c468c0b)

API AppList error

**Response body**
```
{
  "ResponseData": null,
  "Error": {
    "Code": "Server.SystemError",
    "Message": "system original error",
    "Detail": "list index out of range"
  }
}
```

**Response headers**
```
content-length: 128 
 content-type: application/json 
 date: Wed,23 Aug 2023 01:56:31 GMT 
 server: uvicorn 
```

**Comment by qiaofeng1227** [comment]
## Reason

manage.py's function conbine_list(installing_list, installed_list) bug.


## Temp solution
```
$ docker exec -it websoft9-redis bash
redis-cli
127.0.0.1:6379> FLUSHALL
OK
```
