### ISSUE TITLE
add key authority for API

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#305]
**What type of your feature request?**  

There no any authority for API, it no safe, it must add key authority for API

**Comment by zhaojing1987** [comment]
FastAPI 支持多种认证方法，常用的方法包括基本认证、API 密钥认证、OAuth2 等
1. 基本认证：基于用户名和密码的认证方式，客户端发送请求到服务器，请求头添加：Authorization，其中包含基本认证的凭证信息。凭证信息的格式为 Basic base64(username:password)。服务器接收到请求后，从 Authorization 头部中提取凭证信息，进行解码，并将解码后的用户名和密码与存储在服务器上的用户信息进行比对。
2. API 密钥认证：API 密钥是一种简单的令牌，由服务器生成并分配给访问其 API 的用户。使用者在发起 API 请求时，在请求头中包含他们的 API 密钥。服务器接收到请求后，会检查请求中的 API 密钥是否有效。服务器端需要存储一份有效的 API 密钥列表或在数据库中进行验证。
3. OAuth2：官方参考：[Security FastAPI-tiangolo](https://fastapi.tiangolo.com/zh/tutorial/security/)

**Comment by zhaojing1987** [comment]
API 密钥认证方案：
1、通过cli管理密钥，可以创建和删除密钥，存储到SQLLITE（是否也可以在“设置”里面加入API密钥的管理：创建和删除）
2、FastAPI采用API 密钥认证，在请求中发送API密钥，FastAPI服务从SQLLITE获取密钥进行验证

**Comment by qiaofeng1227** [comment]
apphub容器初期通过apphub cli生成apikey
