### ISSUE TITLE
add websoft9 support at help menu of top menu

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#311]
**What type of your feature request?**  

- [ ] Delete or modify default memu
- [ ] Add websoft9 docs memu 

![image](https://github.com/Websoft9/websoft9/assets/16741975/49e04aff-e363-4847-944f-145089e722b0)

**Comment by qiaofeng1227** [comment]
need test install.sh

**Comment by zhaojing1987** [comment]
Add the following code to shell.override.json:
```
"docs": [
    {
      "label": "Documentation",
      "url": "https://support.websoft9.com/en/docs/"
    }
  ]
```
But it wasn't until Cockpit 297 that this writing method was supported
