### ISSUE TITLE
add nginx location for appmanage's redoc【2】

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#313]
## requirement

Add nginx proxy to reverse container application below

![image](https://github.com/Websoft9/websoft9/assets/43192516/e907d02b-5d6d-49f2-9483-33911ff57448)

## For you reference

* File path: /var/lib/docker/volumes/w9nginxproxymanager_nginx_data/_data/nginx/proxy_host
* sample
```
  location /apidocs/ {
   ...
    proxy_pass       http://websoft9-appmanage:5000/redoc;
  }
```

## Verify it

Once configure successful, we can access it by  http://IP/apidocs

**Comment by laozhou0731** [comment]
```
location /apidocs/static {
  proxy_pass       http://websoft9-appmanage:5000/static;
}
location /apidocs/openapi.json {
  proxy_pass       http://websoft9-appmanage:5000/;
}
location /apidocs/ {
  proxy_pass       http://websoft9-appmanage:5000/redoc;
  sub_filter 'src="/static' 'src="/apidocs/static';
  sub_filter 'spec-url="/' 'spec-url="/apidocs/openapi.json';
}
```

![image](https://github.com/Websoft9/websoft9/assets/62225175/1fc01802-bec8-4e32-9102-9ee0c59e6389)

**Comment by zhaojing1987** [comment]
The url of the API is incorrect：
![image](https://github.com/Websoft9/websoft9/assets/7624828/a5902218-0cd2-4142-806e-3cd5d9d9c7cb)

before add apidocs location into nginx：
![image](https://github.com/Websoft9/websoft9/assets/43192516/81275816-d2b4-4c36-b4bb-af5449c1f792)

**Comment by zhaojing1987** [comment]
修改main.py,增加root_path，如果通过后面通过nginx转发appmanage的api，这个值设置转发的地址即可，例如：
![image](https://github.com/Websoft9/websoft9/assets/7624828/c0837ac3-c9d3-42f6-a78c-ce8458184874)
修改后的显示为：
![image](https://github.com/Websoft9/websoft9/assets/7624828/52ae9989-a372-4cd5-a039-2f25da242e3e)

**Comment by laozhou0731** [comment]
location /apidocs/static {
  proxy_pass       http://websoft9-appmanage:5000/static;
  sub_filter 'e.hideHostname' 'true';
  sub_filter_types text/javascript;
}

![image](https://github.com/Websoft9/websoft9/assets/62225175/26cd834c-5515-4c8f-8d5a-745e9da4d54d)
