### ISSUE TITLE
Nginx proxy Manager restart need all proxy service is available

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#325]
**What type of your feature request?**  

Nginx proxy Manager restart need all proxy service is available, otherwise Nginx proxy Manager can not start.   
It mean all applications cannot.

**Is your feature request related to a problem? Please describe.**  
Nginx proxy Manager automatilly repair them

**Comment by qiaofeng1227** [comment]
If add proxy by nginx proxy manage console, it can automatically check the backend service status.
if service configure have grammatical error, NPM will make it offline at console and delete config file  at nginx config directory
