### ISSUE TITLE
file browser error at CentOS Stream9/Fedora37/Ubuntu22.04

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#335]
**Describe the bug**

![image](https://github.com/Websoft9/websoft9/assets/16741975/5e73be1a-e2ab-4cd0-a24d-392d48891e56)

**Comment by qiaofeng1227** [comment]
If you use **wget and unzip** to install plugin, navigate is ok.
(I test on CentOS Stream9/Fedora37/Ubuntu22.04)

**Comment by qiaofeng1227** [comment]
how to fixed:
1. use shell
2. use python, add **chmod +x -R /usr/share/cockpit/navigator/scripts**

```
find /usr/share/cockpit -type f -name "*.py3" -exec dirname {} \; | uniq | xargs -I {} chmod +x -R {}
```
