### ISSUE TITLE
add personalized nginx config into  nginxproxymanage

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#338]
some app,such as magento need extra nginx config, how to support it on appmange api?

**Comment by zhaojing1987** [comment]
![image](https://github.com/Websoft9/websoft9/assets/7624828/84f7290f-6c5a-4372-963f-bdb9eaa9d473)

like this：
![image](https://github.com/Websoft9/websoft9/assets/7624828/ed6e5760-da7d-4a2b-8bbd-8c26b329e87f)
