### ISSUE TITLE
websoft9 api docs publish

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#339]
**Describe the bug**

- [x] css/js files of Redocs is get on CDN, it is very slowly. it need download to Docker image

- [x] publish api static site to support.websoft9.com 
- [x] Static website
      - build at build_apphub.yml
      - how to build json file?  @zhaojing1987 
      - redoc.standalone.js
      - [static html](https://redocly.com/docs/redoc/deployment/html/)  √

- [x] Nginx proxy for /docs   @zhaojing1987

**Comment by qiaofeng1227** [comment]
[wagger-ui dist](https://github.com/swagger-api/swagger-ui.git)
[redoc.standalone.js](https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js)
