### ISSUE TITLE
get all containers version

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#38]
**What type of your feature request?**  

get all containers version

**Comment by chendelin1982** [comment]
1. target list [appname, redis, mysql, mariadb]
  * 应用清单与容器清单的 compose 匹配（镜像名，容器名，服务名）
  * 匹配成功，将应用[i]和容器名 加入到 target list
3. loop running get_version.sh

**Comment by qiaofeng1227** [comment]
```
~ docker compose -p docker-nextcloud ps --services
nextcloud
mysql
redis

```
