### ISSUE TITLE
improve all actions

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#393]
- [x]     "docker-library"
- [x]     "websoft9"
- [x]     "portainer":
- [x]     "nginx"
- [x]     "gitea"
- [x]     "myapps"
- [x]     "appstore"
- [x]     "settings"
- [x]     "navigator"
- [x]     "media"

![Image](https://github.com/Websoft9/websoft9/assets/16741975/5c78ffa3-6d29-4862-8426-07b5fcb1ca9a)

![Image](https://github.com/Websoft9/websoft9/assets/16741975/821fde3f-d428-48af-adbe-ec90e61e2af7)

**Comment by chendelin1982** [comment]
The correct case for **files**   
```
files: |
  - media.json
  - docs/*.pdf
```
