### ISSUE TITLE
can not connect Gitea at websoft9 (use domain:9000 access Cockpit)

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#414]
**Describe the bug**

![image](https://github.com/Websoft9/websoft9/assets/16741975/a314cd6b-ad3e-4f74-b4c3-bb5c8a8a67ef)
![image](https://github.com/Websoft9/websoft9/assets/16741975/1f584c5e-69ea-4da3-96d3-97b39afe0013)

I have do some research for this problem:

- http://cdl.websoft9.cn/w9git/  is ok
- credentials is ok
- portainer, nginx can access

**Comment by zhaojing1987** [comment]
This bug has been fixed
