### ISSUE TITLE
force user set power password when create user at Linux or Cockpit

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#417]
**What type of your feature request?**  

- [ ] Use PAM (Pluggable Authentication Modules) to solve it
- [ ] Password strategy: 1 Upper letter....

**Comment by chendelin1982** [comment]
solution for reference:
![image](https://github.com/Websoft9/websoft9/assets/16741975/e6bc15cd-6542-4f58-b825-00091586c9a8)

**Comment by qiaofeng1227** [comment]
cockpit have this power password function in it.
