### ISSUE TITLE
Shorten random string of APP_ID

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#418]
**What type of your feature request?**  

![image](https://github.com/Websoft9/websoft9/assets/16741975/ffee6fda-50ba-4d59-930b-e5506f1ec85d)

参考其他url随机化，建议缩短为4-5位，包含数字以降低重复的可能

**Comment by zhaojing1987** [comment]
已修改为：数字+小写字母，随机5位，(Portainer不支持大写字母,它会自动将大写字母转换为小写字母，所以排除大写字母)
