### ISSUE TITLE
全新安装成功后显示Error : Network Error

### ISSUE THREAD

**Issue by rzzhuzhen** [Websoft9/websoft9#434]
我在腾讯云 Ubuntu22.04.3 上，sudo -i 后按照安装文档执行
wget -O install.sh https://websoft9.github.io/websoft9/install/install.sh && bash install.sh
安装成功后，打开 ip:9000后，提示错误

<img width="1255" alt="截屏2023-12-10 12 55 50" src="https://github.com/Websoft9/websoft9/assets/3971372/7d11f3b9-59a9-483d-bb14-6c975a9751c0">
<img width="1255" alt="截屏2023-12-10 12 55 31" src="https://github.com/Websoft9/websoft9/assets/3971372/41bf9155-2e5a-435f-85ba-26920fe6d7a5">
<img width="1255" alt="截屏2023-12-10 12 55 09" src="https://github.com/Websoft9/websoft9/assets/3971372/8661479b-b449-4e9d-b0c7-fb33f4698998">

**Comment by qiaofeng1227** [comment]
是腾讯云ubuntu22.04吗，我验证一下。

```
sudo su
wget -O install.sh https://websoft9.github.io/websoft9/install/install.sh && bash install.sh
```

我验证是可以正常打开对应页面的。如果执行命令不一样，请参照我们上面的命令。

**Comment by chendelin1982** [comment]
现在还不是很清楚 sudo -i   与 sudo su 切换后的差异 @rzzhuzhen

**Comment by rzzhuzhen** [comment]
仔细检查，发现安装时有一条错误信息：
Installing cockpit-session-recording
E: Unable to locate package cockpit-session-recording
cockpit-session-recording failed to install

**Comment by qiaofeng1227** [comment]
为了能够适应所有的操作系统，我们把所有包列出来安装，可能有些包在部分操作系统下没有，重定向了错误，不会停止安装

**Comment by rzzhuzhen** [comment]
我从官网下载了 cockpit-session-recording的安装包，make install都正常，但问题还是没有解决。
同时又检查发现一个潜在的错误。
fwupd-refresh.service is not running.
我是用wsl2重新安装的系统，这是不是意味着安装包不支持Ubuntu22.04.3？

**Comment by chendelin1982** [comment]
not reply, closed
