### ISSUE TITLE
customer install websoft9 failed on debian12

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#452]
Debian12 全新安裝 應用商店打不開 顯示網路錯誤

伺服器在台灣 本地私有化部署 部署虛擬機PVE8.1

日誌：

02:34
Failed to start polkit.service - Authorization Manager.systemd

02:34
/usr/lib/tmpfiles.d/polkitd.conf:3: Failed to resolve user 'polkitd': No such processsystemd-tmpfiles

**Comment by qiaofeng1227** [comment]
使用 阿里云 debian12测试能够正常安装websoft9

**Comment by chendelin1982** [comment]
> polkit.service

Websoft9 控制台依赖 polkit.service 这个服务，如何虚拟机中没有这个服务，请自行安装后再试
