### ISSUE TITLE
create demo server of Websoft9

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#455]
**What type of your feature request?**  

- [ ] create application quick and stable
- [ ] docker volume change to nas
- [x] access by domain（don't use websoft9 domain, godaddy aws）
- [ ] account security
- [ ] cost
- [ ] application dead time

**Comment by qiaofeng1227** [comment]
select domains:
goweb.cc

**Comment by qiaofeng1227** [comment]
1. docker image and volume data transfer to data disk
2. backup data disk erveryday, backup system disk init?

**Comment by qiaofeng1227** [comment]
```
# 查看新磁盘的设备名(数据盘是/dev/sdb)
lsblk

# 创建挂载目录
sudo mkdir /var/lib/docker

# 格式化新磁盘（如果是新磁盘或你想重新格式化）
sudo mkfs.ext4 /dev/sdb

# 挂载新磁盘
sudo mount /dev/sdb /var/lib/docker

# 可选: 使挂载在重启后持久化
echo '/dev/sdb /var/lib/docker ext4 defaults 0 0' | sudo tee -a /etc/fstab
```
