### ISSUE TITLE
all app container exec error on portainer

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#464]
**Describe the bug**

exec to container by Portainer, can not used

![image](https://github.com/Websoft9/websoft9/assets/16741975/cb9dddc0-82fb-4abd-8f06-a44eb34fb351)

**Comment by chendelin1982** [comment]
run official image on RockyLinux, the same error

**Comment by qiaofeng1227** [comment]
It's not Linux os problem.

Portainer 2.19.x and 2.20.0 can not  support docker 26.0.

https://www.portainer.io/blog/portainer-and-docker-26
https://github.com/portainer/portainer/issues/11436
