### ISSUE TITLE
image have pulled at host, can not create application when host not have Internet IP?

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#467]
**Describe the bug**

image have pulled at host, can not create application when host not have Internet IP?

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/websoft9/assets/16741975/d1a9aeb1-4547-4b99-8cda-21abea32d853)
disable internet

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/websoft9/assets/43192516/5d484d4c-7161-45f2-af49-c4a29feb0f27)

**Comment by qiaofeng1227** [comment]
禁止互联网后，wordpress还是正常能安装（已下载镜像）。

**Comment by chendelin1982** [comment]
Testing step:

1. Create ECS with Websoft9 wordpress image and not create Internet IP
2. Use local IP access this ECS

**Comment by qiuf12** [comment]
Access  success.

<img width="703" alt="image" src="https://github.com/user-attachments/assets/810bc737-6307-4224-97ef-45d3af67f0ff" />

<img width="929" alt="g1" src="https://github.com/user-attachments/assets/ad7d5ede-8f93-401e-8c66-702a746a68e5" />

<img width="892" alt="image" src="https://github.com/user-attachments/assets/dfe2b2cc-e198-4f68-8733-8922c29a29f2" />
