### ISSUE TITLE
add config item for running apps number

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#472]
**What type of your feature request?**  

add config item for running apps number.

When install app at appstore, it need check the number limit, then can install or not permit install

**Comment by qiaofeng1227** [comment]
How to count apps:
1. portains's apps api return datas and  app is active
2. this app_id in the gitea project

**Comment by zhaojing1987** [comment]
怎么判断某个应用是"正在运行"？

**Comment by qiaofeng1227** [comment]
目前在开发环境上测试通过

**Comment by chendelin1982** [comment]
提示信息：运行的应用数量超过免费版限制，请[升级](https://www.websoft9.com/pricing)到商业版本
