### ISSUE TITLE
When W9_HTTP_PORT=$other_env or W9_HTTPS_PORT=$other_env, create domain error

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#475]
**What type of your feature request?**  

When W9_HTTP_PORT=$other_env or W9_HTTPS_PORT=$other_env, create domain error. I think when use any ENV from .env file, should check this ENV is =value or =$other_env

**Comment by qiaofeng1227** [comment]
测试完毕，ok

**Comment by qiaofeng1227** [comment]
安装时能够适应。但是重建时无法。

![image](https://github.com/Websoft9/websoft9/assets/43192516/71d47a4f-53b5-4f67-a12f-510bed77ab81)

![image](https://github.com/Websoft9/websoft9/assets/43192516/0b2637da-de7e-453e-90d9-3ae1020bea3b)
