### ISSUE TITLE
favorite app

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#478]
**What type of your feature request?**  

favorite apps have priority display at AppStore
![image](https://github.com/Websoft9/websoft9/assets/16741975/23ca8752-213c-4492-bbba-92f5f880af50)

- [ ] set or cancel favorite apps from apphub cli or api or..?
- [ ] user can set or cancel favorite apps at appstore

**Comment by qiaofeng1227** [comment]
应该有收藏和取消收藏两个cli或者api，点击收藏，再次点击取消收藏
