### ISSUE TITLE
Doc url in the app store and myapps should be updated to the next version

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#484]
**Describe the bug**

- The application document url in the app store and myapps should be updated to the next version
- The translation of the English version of the document is incorrect

![image](https://github.com/Websoft9/websoft9/assets/62225175/412d510b-5fbe-41cb-85d5-93ba08c43c3e)

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/websoft9/assets/16741975/485c8b5e-d626-419f-92e5-721e4e908d84)

Add two link:

- 官网（Website）
- 文档（Documentation）

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/websoft9/assets/16741975/7a93202e-214a-4254-8404-683b60eca7e4)

**Comment by qiaofeng1227** [comment]
my apps's documentation should be detail app of docs
