### ISSUE TITLE
add a WeChat communication group to share via QR code

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#486]
Add a communication and consultation area in Readme: add a WeChat communication group to share via QR code

**Comment by qiaofeng1227** [comment]
refer to: https://github.com/websoft9op/company/issues/149

**Comment by qiaofeng1227** [comment]
add wechat group in https://www.websoft9.com/contact-us

用户交流（企业微信群）[https://libs.websoft9.com/Websoft9/feature/icon-userchatgroup-websoft9.png]

**Comment by zhaojing1987** [comment]
![image](https://github.com/Websoft9/websoft9/assets/7624828/9a631bde-e4b9-4c6f-b484-f5cc2f278197)
在contentful中对应位置新增新的数据后，重新执行action发布即可

**Comment by qiaofeng1227** [comment]
add data in contentful
