### ISSUE TITLE
nextcloud set https at private cloud, access always waiting

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#492]
**Describe the bug**

```
Refused to send form data to url' because it violates the following Content Security Policy directive: "form-action 'self'".
```

![image](https://github.com/Websoft9/websoft9/assets/16741975/837f3c8b-f0c4-457e-919f-3757322ae4ba)

**Comment by qiaofeng1227** [comment]
https
![image](https://github.com/Websoft9/websoft9/assets/43192516/0527ee23-f68c-4cd1-b9e2-97787c851ebd)

http
![image](https://github.com/Websoft9/websoft9/assets/43192516/64935005-b5e0-46d8-bae1-5d689916afcb)

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/websoft9/assets/43192516/2892eafd-cade-4bae-bb89-8f30fd4ffea4)

**Comment by qiaofeng1227** [comment]
https://hub.docker.com/_/nextcloud

```
NEXTCLOUD_TRUSTED_DOMAINS="\*"
NEXTCLOUD_ADMIN_USER=admin
NEXTCLOUD_ADMIN_PASSWORD=$W9_POWER_PASSWORD
#When your domain name uses an SSL certificate, you need to make it effective and then rebuild the application
#OVERWRITEPROTOCOL=https
```

**Comment by chendelin1982** [comment]
docs?
