### ISSUE TITLE
Can accessing port 80 be more user-friendly when using Websoft9

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#499]
Can accessing port 80 be more user-friendly when using Websoft9
![image](https://github.com/Websoft9/websoft9/assets/62225175/ecaaf570-5ce0-4642-8b74-134023f084fd)

**Comment by chendelin1982** [comment]
客户直接输入IP地址，发现 502，就删除镜像了。故，一个友好的提示，非常重要

**Comment by chendelin1982** [comment]
Have adding landing page to it, it need to add correct NGINX configurations at `initproxy.conf` file  @zhaojing1987

**Comment by zhaojing1987** [comment]
修改initproxy.conf配置
```
 location / {
      root /etc/websoft9/landing;
      index index.html
      # Proxy!
      include conf.d/include/proxy.conf;
  }
```
![image](https://github.com/user-attachments/assets/f756d541-3338-4b3e-aad3-59b8378f8b9e)

同时建议将 文件夹landing放入：default_www 目录

**Comment by qiaofeng1227** [comment]
test it ok， can close the issue
