### ISSUE TITLE
Configure Docker image acceleration

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#502]
Configure Docker image acceleration

- [x] prepare other registry for Websoft9 image
- [x]  prepare other registry  docker-library
- [x] add registry-mirrors at "Settings" （设置页面追加镜像加速地址）

**Comment by chendelin1982** [comment]
Portainer Registries?
```
docker run -d -p 5000:5000 --name registry \
  -e http_proxy=http://<proxy-host>:<proxy-port> \
  -e https_proxy=http://<proxy-host>:<proxy-port> \
  -v $(pwd)/config.yml:/etc/docker/registry/config.yml \
  -v /var/lib/registry:/var/lib/registry \
  registry:2

```

**Comment by qiaofeng1227** [comment]
how to do it:
### from portainer
1. portainer set registries
![fa41f71848124da2191929ffe9b4f36](https://github.com/Websoft9/websoft9/assets/43192516/8e2287db-1470-4760-ba9b-b56fb2be3372)
2. portainer stack deploy use this registry?
![792b6eefee551b3b211a7289a220486](https://github.com/Websoft9/websoft9/assets/43192516/6d5abbd8-57cd-4fcb-bdc0-7c0497d7f32e)


### apphub or cockpit

control host to update docker config file?

**Comment by qiaofeng1227** [comment]
初期显示
1. 当 /etc/docker/daemon.json 不存在或者 这个文件的 registry-mirrors节点对应的加速地址为空时，页面无显示。
2.  registry-mirrors节点对应的加速地址存在时，根据数组来列表多行显示

更新：
当页面地址为空时，清空registry-mirrors节点；
当页面地址不为空，如果文件存在并且registry-mirrors节点 存在，将其作为数组更新到registry-mirrors节点；如果文件不存在或者registry-mirrors节点不存在，新增文件和registry-mirrors节点，将页面数组地址赋值给registry-mirrors
更新后为了docker生效，需要执行(这个过程让用户自行去做，页面上给用户提示)
```
sudo systemctl daemon-reload
sudo systemctl restart docker
```

Json格式：
```
{
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "10m",
        "max-file": "5"
    },
   "registry-mirrors": ["https://docker.rainbond.cc","https://registry.inner.websoft9.cn"]
}
```

**Comment by yuanssssss** [comment]
OK，cockpit我之前在centos上体验过，也在ubuntu上面安装过，然后我配置镜像的话是编辑daemon.json文件，通过docker info去查看的。我等下尝试去用cockpit



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月26日 10:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [Websoft9/websoft9] Configure Docker image acceleration (Issue #502) |

建议采用cockpit来操作宿主机：
1，默认当docker设置了仓库加速地址，显示在页面，多个地址多行显示
2，可以编辑和删除已有地址（包括在原有地址上增加），更新到/etc/docker/daemon.json

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/websoft9/assets/43192516/d650bc82-f184-4091-bf07-362cb637702e)
