### ISSUE TITLE
optimize install Docker

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#503]
- use docker official install.sh
- if can not use it
  - set repo for OS distribution
  - intall (try many time if network slow)
  - improve daemon.json of docker

**Comment by qiaofeng1227** [comment]
1. nginx 代理方案（内部香港ECS）
2. rainbond镜像仓库方案

**Comment by qiaofeng1227** [comment]
目前通过修改/etc/docker/daemon.json, 能够设置镜像加速仓库。

是否 【 DOCKER_OPTS】【dockerd --registry-mirror】通过环境变量或者dockerd cli来实现。

**Comment by zhaojing1987** [comment]
经调查：
1、修改配置文件：/etc/docker/daemon.json 的方式，需要重启docker，对于生产环境来说有很大风险
2、DOCKER_OPTS 是属于早期docker的环境变量，现在不支持
3、dockerd命令用于启动docker的守护进程，如果手动配置参数启动，比如加速仓库，就意味着不受系统服务控制管理了（例如systemctl），所以通过这个命令来进行加速会更加复杂：
```
--停止docker
systemctl stop docker
systemctl stop docker.socket

--手动启动docker守护进程，并设置加速
nohup dockerd --registry-mirror=加速地址 &

--如果删除加速：手动终止守护进程
ps aux | grep dockerd
kill -9 id

--重启docker
systemctl restart docker
```

**Comment by zhaojing1987** [comment]
另外一种可能得方案，就是在docker compose的中，配置完整的镜像路径，例如：mirror-address/library/image:tag

比如可以在.env中设置环境变量：
```
W9_IMAGE_REPO=docker.rainbond.cc/library
W9_REPO=$W9_IMAGE_REPO/wordpress
```

W9_IMAGE_REPO 的设置可以通过 “设置” 配置，写入配置文件，每次安装应用的时候判断是否有加速地址，如果有就在安装前修改.env,加入W9_IMAGE_REPO 


这种方式：
优点：
1、可以不用修改docker的配置文件和重启docker，减少对生产环境的影响；
2、 不是全局修改，不影响docker本身，加速只针对websoft9的应用安装；
缺点：
1、需要改造 docker-library 的项目，有些镜像的配置是通过W9_REPO，有些是固定的；
2、需求改造apphub以适用；
3、如果用户在“设置”中删除加速地址，那么已经安装的应用配好的加速地址将无法删除，可能会影响重建；

**Comment by chendelin1982** [comment]
optimze

1. use `sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse"` replace 
```
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

2. need fix
```
        if [ $dnf_status -eq 0 ]; then
            sudo dnf install yum-utils -y
            sudo dnf config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
            sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

**Comment by qiaofeng1227** [comment]
```
[root@iZbp11u08t2q9nlzquf6gnZ ~]# dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
Adding repo from: https://download.docker.com/linux/fedora/docker-ce.repo
Curl error (28): Timeout was reached for https://download.docker.com/linux/fedora/docker-ce.repo [Failed to connect to download.docker.com port 443 after 15200 ms: Connection timed out]
```

**Comment by chendelin1982** [comment]
refer to: https://github.com/Websoft9/websoft9/issues/547
