### ISSUE TITLE
websoft9 service can not send credentials to Nginx or portainer reset 

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#505]
**What type of your feature request?**  

![image](https://github.com/Websoft9/websoft9/assets/16741975/7ff276de-bc94-471c-8fb4-061d4acf6bba)

**Comment by qiaofeng1227** [comment]
微服务之间协调机制与工具

- 注册发现
[consul](https://hub.docker.com/_/consul)
[zookeeper](https://hub.docker.com/_/zookeeper)

**Comment by qiaofeng1227** [comment]
```
docker compose -p websoft9 down -v
docker compose -p websoft9 up -d
systemctl restart websoft9
```

**Network Error**, 


```
docker restart websoft9-proxy
```

container OK.
