### ISSUE TITLE
help wanted at Websoft9 console

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#507]
**What type of your feature request?**  

![image](https://github.com/Websoft9/websoft9/assets/16741975/0348a931-018d-4a1a-8e02-877ffaaf604b)

**Comment by qiaofeng1227** [comment]
添加加速地址或域名的解释说明，需要查看详细的内容。是否前端有合适的组件，选用合适的组件来做

**Comment by qiaofeng1227** [comment]
Tooltip（工具提示）是一种常见的用户界面元素，用于在用户悬停或点击某个元素（如按钮、链接、图标等）时显示额外的信息或提示。Tooltip通常以小弹出框的形式出现，包含简短的文本说明，有时还会包括图片或其他元素。

**Comment by qiaofeng1227** [comment]
![企业微信截图_17199920917689](https://github.com/Websoft9/websoft9/assets/43192516/225b0b4d-05f8-4049-8127-d448c4948281)

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/websoft9/assets/43192516/2cb9db90-3843-49b5-9cbe-01d9b95abb14)

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/websoft9/assets/43192516/f5952ec8-cb1e-4c59-8340-accb53491817)

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/websoft9/assets/16741975/f4c4b4e6-b5ef-4b94-8c9b-46c1f8ae40da)

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/websoft9/assets/16741975/6a2172af-7b6e-4870-a17a-ba41e72fce8f)

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/websoft9/assets/16741975/ee96a6d3-31c2-4820-b7f6-def1574a4b4d)

**Comment by chendelin1982** [comment]
Three solution :
- tooltip
- documentation
- docs windows

**Comment by chendelin1982** [comment]
![image](https://github.com/Websoft9/websoft9/assets/16741975/23650842-8c09-4a18-bf34-2ea5f273d610)
links error, and need i18n

**Comment by qiaofeng1227** [comment]
wildcard domain link：
https://support.websoft9.com/docs/next/domain-prepare#wildcard
https://support.websoft9.com/en/docs/next/domain-prepare#wildcard

appstore page documentation link：(e.g. gitlab)
https://support.websoft9.com/docs/next/gitlab
https://support.websoft9.com/en/docs/next/gitlab
