### ISSUE TITLE
websoft9-proxy container delete， cannot work

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#510]
```
docker compose -p websoft9 down -v
docker compose -p websoft9 up -d
systemctl restart websoft9
```

**Network Error**, use proxy container's account can login to nginxproxymanage.

```
docker restart websoft9-proxy
```

container OK.

**Comment by qiaofeng1227** [comment]
delete initproxy.conf migration, set config file in the real path in docker image, not in container entrypoint

**Comment by chendelin1982** [comment]
customize conf?

**Comment by qiaofeng1227** [comment]
initproxy.conf have customer block:
```  
# Custom
  include /data/nginx/custom/server_proxy[.]conf;
```

- /data/nginx/custom/server_proxy[.]conf will not overload the initproxy.conf
- The contents of the source and included files are merged together to form the final configuration

**Comment by chendelin1982** [comment]
fixed
