### ISSUE TITLE
websoft9 proxy: 80->9000

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#511]
User access by ip in brower, it will show 500 now.

Can we set proxy on nginxproxymanage, convert 80 to 9000?

**Comment by zhaojing1987** [comment]
修改nginx中 " location / "，通过 301 进行重定向：
![image](https://github.com/Websoft9/websoft9/assets/7624828/178649af-2130-4c80-9498-65e3d2fc7eb6)

连锁反应：
301重定向为固定9000端口，当用户修改cockpit的端口为非 9000 时，重定向会引发问题
