### ISSUE TITLE
Internship plan for [Shi min]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#517]
Intership use [Github issues](https://github.com/Websoft9) for task management.

Start time: Jul 22, 2024  
End time:  

### Technical Tasks

- [ ] Documentation translation
- [ ] Create docker compose library
- [ ] Create Terraform templates for installing Websoft9 in major Cloud

### Daily Operational

- [ ] Build image
- [ ] Marketing contents

### Team study and presentation

- [ ] [Stye Guide](https://docs.gitlab.com/ee/development/documentation/)
- [ ] [Docker Compose](https://docs.docker.com/compose/)
- [ ] [Terraform](https://www.terraform.io/)

## Checkpoint

- [ ] A Daily Check-In With The Intern
- [ ] Weekly Meeting/Video Call With The Intern
- [ ] Weekly Project Checkpoint
- [ ] Pre-Program Evaluation 
- [ ] End-of-Program Evaluation

**Comment by qiaofeng1227** [comment]
## 2024  September 2nd work plan：

1. improve English docs of app
- [x]  gitea
- [x]  gitlab
- [x]  gogs
- [x]  grafana
- [x]  graphite
- [x]  graylog
- [x]  haproxy
- [x]  homeassistant
- [x]  huginn
- [x]  humhub

2. Write a [Terraform](https://www.terraform.io/) example which can be create a ESC by websoft9 product
Detail refer to: https://github.com/Websoft9/CloudForms/issues/3

**Comment by qiaofeng1227** [comment]
## 2024  September 3rd work plan：

1. improve English docs of app

- [x] influxdb
- [x] jellyfin
- [x] jenkins
- [x] jetty
- [x] jihu
- [x] jitsi
- [x] joomla
- [x] jumpserver
- [x] jupyterhub
- [x] kafka

2. Write a [Terraform](https://www.terraform.io/) example which can be create a ESC by websoft9 product
Detail refer to: https://github.com/Websoft9/CloudForms/issues/3

**Comment by qiaofeng1227** [comment]
## 2024  September week4 work plan：

1. improve English docs of app

- [x] kasmweb
- [x] kaspersky
- [x] kibana
- [x] knowage
- [x] kodbox
- [x] koishi
- [x] kong
- [x] logstash
- [x] magento
- [x] manageiq
- [x] mariadb
- [x] matomo

2. Write a [Terraform](https://www.terraform.io/) example which can be create a ESC by websoft9 product
Detail refer to: https://github.com/Websoft9/CloudForms/issues/3


3. Write a docker-compose.yml of **photoprism** app
refer to: [photoprismofficial dock-compose ](https://docs.photoprism.app/getting-started/docker-compose/),[websoft9 rule](https://github.com/Websoft9/docker-library/blob/main/docs/code_owner.md)

**Comment by qiaofeng1227** [comment]
## 2024  September week5 work plan：

- [x] mattermost
- [x] mautic
- [x] mediawiki
- [x] memcached
- [x] metabase

2. Write a docker-compose.yml of **photoprism** app
refer to: [photoprismofficial dock-compose ](https://docs.photoprism.app/getting-started/docker-compose/),[websoft9 rule](https://github.com/Websoft9/docker-library/blob/main/docs/code_owner.md)

**Comment by qiaofeng1227** [comment]
## 2024  October week1 work plan：

- [x] minio
- [x] mongocompass
- [x] mongodb
- [x] moodle
- [x] mosquitto
- [x] mqttx
- [x] mysql
- [x] mysqlworkbench


2. Write a [Terraform](https://www.terraform.io/) example which can be create a ESC by websoft9 product
Detail refer to: https://github.com/Websoft9/CloudForms/issues/3
