### ISSUE TITLE
win10 计划任务运行 ossutil 备份

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#52]
**What type of your feature request?**  

ossutil 是阿里云的备份脚本，现需要通过计划任务自动运行备份

![image](https://user-images.githubusercontent.com/16741975/180917080-26c93506-9502-4ab2-91d9-b6967536dbb8.png)

ossutil 备份 的使用方法：

1. 运行 D:\tools\ossutil\ossutil.bat
2. 然后运行命令 ossutil64.exe sync oss://libs-websoft9-com/Websoft9/ D:\backup\aliyun -f -u

阿里云oss官方文档：https://help.aliyun.com/document_detail/256352.htm

**Comment by LalicNine** [comment]
windows能够有几种方法计划任务
1.给在计划任务窗口操作添加触发器（指定时间运行.bat脚本）
2.在计划任务条件标签栏中能够在计算机空闲一定时间运行脚本
3.启动时运行脚本
4.能够定制多个触发器

参考：https://zhuanlan.zhihu.com/p/115187442

未测试项目：
1、设置脚本运行时长（持续时间）
2、在工作机测试该方案（无法远程连接到工作机）

也可以采取另一种方法（仅能在机器启动时运行脚本）
在运行中输入shell:startup进入启动项目录，将要随系统启动而运行的进程拖拽到内即可在启动时运行该项

参考：https://zhuanlan.zhihu.com/p/446430778

**Comment by LalicNine** [comment]
测试完成：
新建.bat脚本，在计划任务中计划运行，文本如下
cd /d [directory]
ossutil64.exe sync oss://libs-websoft9-com/Websoft9/ D:\backup\aliyun -f -u

后续能够直接设置测试任务属性完成日常需要备份

![微信图片_20220801112444](https://user-images.githubusercontent.com/109707255/182066201-5740d9e8-1d12-48bd-89c0-ff491e052dff.jpg)
