### ISSUE TITLE
cockpit version is old at some ubuntu22.04 distribution

### ISSUE THREAD

**Issue by yuanssssss** [Websoft9/websoft9#523]
**Describe the bug**

When install the websoft9 platform on tencent cloud, the bug occured, it Left ui menu items more than others, it abnormal.

![屏幕截图 2024-08-13 101139](https://github.com/user-attachments/assets/24c596e5-0bcf-40e4-a1a0-45009d2e869e)

## Deployment method

- [x] mcloud

## System Environment

**OS**

- [x] Ubuntu22.x

**Cloud PlatForm**

- [x] 腾讯云

**Comment by zhaojing1987** [comment]
腾讯云没有默认没有加cockpit的安装源： jammy-backports 软件源
解决：安装Websoft9之前，添加软件源(Ubuntu22)
文件：/etc/apt/sources.list 末尾加：
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse

**Comment by chendelin1982** [comment]
```
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse"
```

**Comment by chendelin1982** [comment]
apt install -t ${VERSION_CODENAME}-backports cockpit

Both for install and update

**Comment by chendelin1982** [comment]
need user variable for OS distribution

**Comment by qiaofeng1227** [comment]
```
    elif [ $apt_status -eq 0 ]; then
        export DEBIAN_FRONTEND=noninteractive
        sudo dpkg --configure -a
        sudo DEBIAN_FRONTEND=noninteractive add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu ${VERSION_CODENAME}-backports main restricted universe multiverse"
        apt-get update -y >/dev/null
        apt-get --fix-broken install
        for pkg in $cockpit_packages
        do
            echo "Installing $pkg"
            sudo apt-get install -t ${VERSION_CODENAME}-backports -y "$pkg" > /dev/null || echo "$pkg failed to install"
        done
    else
```

**Comment by chendelin1982** [comment]
fixed
