### ISSUE TITLE
It waiting too long time for App Store when Websoft9 login user not have Docker permission

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#528]
**What type of your feature request?**  

It waiting too long time for App Store when Websoft9 login user not have Docker permission.

Suggest check the permission at the begin of loading, wait for timeout is bad solution

**Comment by chendelin1982** [comment]
- loading media need time, but it not have friendly loading status
- how long for timeout if error

**Comment by zhaojing1987** [comment]
前端跟apphub的通信使用 Axios 组件，该组件的默认超时时间为0毫秒，也就是永不超时，Axios 请求将会一直等待直到服务器响应或网络连接中断

**Comment by chendelin1982** [comment]
fixed
