### ISSUE TITLE
migrate oss artifact from azure blob containers to cloudflare r2 for ￥150

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#530]
1. azure blob  address：https://w9artifact.blob.core.windows.net
2. cloudflare r2 address: https://artifact.websoft9.com
3. directory (cloudflare r2 is the same)
![image](https://github.com/user-attachments/assets/e7c81f7d-6c14-42fc-bdc7-8ec5177f6889)
![image](https://github.com/user-attachments/assets/827733ce-b0e7-47ac-ba6e-01765b4fbf94)
![image](https://github.com/user-attachments/assets/d0c768f7-6e55-44b6-b2a7-7a20e6ddd2a0)

4. secret key sending by other means

5. use rc clone

**Comment by yuanssssss** [comment]
1. install the rclone 
```
sudo -v ; curl https://rclone.org/install.sh | sudo bash
```
2. use the `rclone config` to config the azureblob and the cloudflare r2, you can use the `rclone rcd --rc-web-gui` to check the config, if succuess, you can find the buket derecotory on **Explorer**. such as this.
![image](https://github.com/user-attachments/assets/c67c511d-9b89-451a-9582-fae28db553a4)

3. use the `rclone copy` to migrate from source to distination,you can run this command in a tmux.
```
rclone copy source:sourcepath dest:destpath
``` 
for example,
```
rclone copy azure:/dev cloudflare:/artifact/dev
```

**Comment by chendelin1982** [comment]
solved
