### ISSUE TITLE
Websoft9 安装 RocketMQ 后，域名访问失败  for [RocketMQ]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#532]
**Describe the bug**

Websoft9 安装 RocketMQ 后，域名访问失败  for [RocketMQ]

![image](https://github.com/user-attachments/assets/f28e931b-3ddf-49bd-9b8a-140d227cda18)

![image](https://github.com/user-attachments/assets/dd8f1aee-e4b2-4b30-be81-fbd74e20e448)

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] Ubuntu22.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
rocketmq不是在浏览器直接访问

**Comment by laozhou0731** [comment]
- 有[GUI方案](https://support.websoft9.com/docs/rocketmq/#gui)  RocketMQ-Console-NG，可以在浏览器访问，是项目不够完善
- 如果不提供GUI就不用开放域名设置
