### ISSUE TITLE
add Dockerfile build function for apphub

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#534]
**Function requirement description**    

If application root directory have Dockerfile, it automaticlly build image at below stages on Websoft9 console

- [ ] Run new application
- [ ] Rebuild application

**Technology requirement description**    

- Build image need a long time, so you should consider the timeout
- Where is the dockerfile? It at the application root directory of docker-library, and it maybe have include files from ./src directory or it root directory. So build image need consider these related files
- Suggest try your best to use `docker build` or `docker compose build` because use can not need to study new rules

**Related knowledge for your reference**    
- `docker build` or `docker compose up` and `docker compose build` can build image
- If Dockerfile not modified, docker compose will not build it again
- Portainer stack not have build api
- Portainer image have build api
- Is there have `docker compose` cli at Portainer container?

**Comment by qiaofeng1227** [comment]
It can build dockerfile by websoft9 logic now
