### ISSUE TITLE
Create dockerhub proxy URL based on Cloudflare

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#536]
**What type of your feature request?**  

Use **Cloudflare Worker** or **Cloudflare Load Balancer** to proxy below DockerHub URLs, then user can add a stable URL at registry-mirrors configuration

```
https://docker.rainbond.cc
https://docker.1panel.dev
https://docker.fxxk.dedyn.io
https://a.ussh.net
https://docker.zhai.cm
```

**Comment by qiaofeng1227** [comment]
- [x] install.sh
- [x] mcloud

**Comment by chendelin1982** [comment]
fixed
