### ISSUE TITLE
Build and push js file to CloudFlare worker

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#538]
## What type of your feature request?

Create Cloudflare worker to deploy for Dockerhub proxy

- [x] Create Cloudflare worker and test [work.js](https://github.com/Websoft9/websoft9/blob/main/docker/cloudflare.js)
- [x] Binding domain for Cloudflare worker `dockerhub.websoft9.com`
- [x] Complete work.js aotumaticlly [build action]

- [x] Optimize the **load balancing** for [work.js](https://github.com/Websoft9/websoft9/blob/main/docker/cloudflare.js)

**Comment by zhaojing1987** [comment]
使用方法：https://github.com/cmliu/CF-Workers-docker.io 
action ：https://github.com/Websoft9/websoft9/actions/workflows/dockerhub_proxy.yml

**Comment by chendelin1982** [comment]
completed
