### ISSUE TITLE
add WAF ability for Websoft9-Proxy

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#546]
**What type of your feature request?**  

Open source WAF for Nginx, optional:

- [ ] ModSecurity
- [ ] ngx_http_limit_req_module 限制每秒请求数
- [ ] ngx_http_limit_conn_module 限制IP连接数
- [ ] http_limit_conn和http_limit_req模块
- [ ] ngx_lua_waf 基于ngx_lua的web应用防火墙，使用简单，高性能和轻量级
- [ ] http_guard 基于openresty
- [ ] other WAF software with web console, and can integrated with Nginx

- NPM custome config: https://nginxproxymanager.com/advanced-config/
- Nginx against DDos: https://webhostinggeeks.com/howto/nginx-ddos-attack-tutorial/
- Aliyun WAF: https://www.aliyun.com/product/waf
- 雷池 WAF: https://docs.waf-ce.chaitin.cn/
- openappsec: https://docs.openappsec.io/getting-started/start-with-docker/install-with-docker-locally-managed  
- 南墙

**Comment by zhaojing1987** [comment]
雷池docker compose [安装](https://docs.waf-ce.chaitin.cn/zh/%E4%B8%8A%E6%89%8B%E6%8C%87%E5%8D%97/%E5%AE%89%E8%A3%85%E9%9B%B7%E6%B1%A0/%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85)

**Comment by zhaojing1987** [comment]
为nginx增加  ngx_http_limit_req_module   和 ngx_http_limit_conn_module   配置方法：
1、在nginx挂载目录下(/var/lib/docker/volumes/websoft9_nginx_data/_data/nginx)，新增 custom 文件夹 
2、在文件夹下新建 http.conf 文件：
```
limit_req_zone $binary_remote_addr zone=w9_limit_req_zone:10m rate=30r/s;
limit_conn_zone $binary_remote_addr zone=w9_limit_conn_zone:10m;

```
说明：
zone=w9_limit_req_zone:10m              定义一个名称为 w9_limit_req_zone 的共享内存区域用于存储每秒每秒请求信息，大小10M
rate=30r/s:                                           每个IP地址的请求速率限制为每秒30个请求
zone=w9_limit_conn_zone 10m;          定义一个名称为 w9_limit_conn_zone 的共享内存区域用于存储IP连接信息，大小10M

3、使用
上面的步骤是全局定义，并没有使用(生效)。如果要给应用配置并使生效，需要进入 nginx proxy manager 进行配置：
![image](https://github.com/user-attachments/assets/c0f13867-a445-4df0-89ab-379084508eaa)
```
limit_req zone=w9_limit_req_zone burst=50 nodelay;
limit_conn w9_limit_conn_zone 30;
```
说明：
limit_req zone=w9_limit_req_zone burst=50 nodelay;   表示设置 限制每秒请求数 为之前定义的全局参数 w9_limit_req_zone，burst=50 表示应对 突发流量（允许在短时间内突发性地允许额外的请求(总请求数为rate+burst：30 + 50 )）
nodelay 表示如果请求超过了速率限制，立即返回503 错误（服务不可用）

limit_conn w9_limit_conn_zone 30;  表示每个 IP 地址最多可以同时建立30个连接

以上默认规则是基于以下条件作为参考设置：
同时在线用户数在 100 - 200 人左右，且每个用户每秒操作次数不超过 1 - 2 次；
假设每个用户可能会同时打开 2 - 3 个页面或功能模块；

具体配置需要根据服务器配置以及应用常规请求数的实际需求调整修改！！！

**Comment by zhaojing1987** [comment]
可能得测试方法：ab测试
1、安装测试工具：
```
apt-get update
apt-get install apache2 - utils
```
2、测试命令：ab -n [请求总数] -c [并发数] [目标URL]
```
ab -n 500 -c 50  http://websoft9.com/
```
可以将上面的参数：rate  burst 同时连接数，都调整到最小，比如 1 来测试实际效果，可在nginx的日志中查看访问控制的情况

**Comment by zhaojing1987** [comment]
开源 WAF：[bunkerweb](https://www.bunkerweb.io/)  仓库地址：https://github.com/bunkerity/bunkerweb
开源安全平台(包含WAF)：[wazuh](https://wazuh.com/)   仓库地址：https://github.com/wazuh/wazuh-docker
