### ISSUE TITLE
Optimize install_docker.sh 

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#547]
**What type of your feature request?**  

Need to test CenOS repository

- [ ] centos.8|centos.7|rhel.7 (In get.docker.com)
- [ ] oracleLinux7,Oracle Linux8 (rhel family)

Extra OS may need to focus:

- [ ] Oracle Linux9
- [ ] Amazon Linux (?)
- [ ] rhel's son: AlmaLinux(), RockyLinux

> rhel's father:  Fedora (is the father of CentOS Stream), CentOS Stream

**Comment by qiaofeng1227** [comment]
test support by docker official shell:
```
curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
```

- [x] OracleLinux7  not support
- [x] OracleLinux8  not support
- [x] OracleLinux9 not support
- [x] Centos7 error
- [x] Centos8 ok 
- [x] CentOSStream9 ok
- [x] CentOSStream8 error
- [ ] Redhat7

**Comment by jinsheng200303** [comment]
### CentOSStream8 Error
```
[root@iZbp10aie1w0cecjb5dxk6Z ~]# curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
# Executing docker install script, commit: 711a0d41213afabc30b963f82c56e1442a3efe1c

DEPRECATION WARNING
    This Linux distribution (centos 8) reached end-of-life and is no longer supported by this script.
    No updates or security fixes will be released for this distribution, and users are recommended
    to upgrade to a currently maintained version of centos.

Press Ctrl+C now to abort this script, or wait for the installation to continue.
+ command_exists dnf5
+ command -v dnf5
+ command_exists dnf
+ command -v dnf
+ sh -c 'dnf -y -q --setopt=install_weak_deps=False install dnf-plugins-core'
Error: Failed to download metadata for repo 'extras-common': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=extras-extras-common [Could not resolve host: mirrorlist.centos.org]
```

### CentOS7.9 Error
```
[root@iZbp176kpvms8ifg8s165zZ ~]# curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
# Executing docker install script, commit: 711a0d41213afabc30b963f82c56e1442a3efe1c

DEPRECATION WARNING
    This Linux distribution (centos 7) reached end-of-life and is no longer supported by this script.
    No updates or security fixes will be released for this distribution, and users are recommended
    to upgrade to a currently maintained version of centos.

Press Ctrl+C now to abort this script, or wait for the installation to continue.
+ command_exists dnf5
+ command -v dnf5
+ command_exists dnf
+ command -v dnf
+ sh -c 'yum -y -q install yum-utils'
Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version
+ sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] curl#35 - "TCP connection reset by peer"
```

**Comment by zhaojing1987** [comment]
官方安装脚本支持的操作系统及版本：

| **Ubuntu**           | **Debian(Raspbian)**           | **CentOS** | **RHEL** | **Fedora** |
|----------------------|----------------------|------------|----------| ---------- |
  | 22.04 (jammy)        | 12 (bookworm)        | 8          | 8        |39 及以上版本|
  | 20.04 (focal)        | 11 (bullseye)        | 7          | 7        ||
 | 18.04 (bionic)       | 10 (buster)          |            |          ||
 | 16.04 (xenial)       | 9 (stretch)          |            |          ||
 |                      | 8 (jessie)           |            |          ||

以下发行版和版本会触发弃用通知(中断10秒后继续执行安装)：

|  **CentOS**  |  **RHEL**   | **Debian(Raspbian)**           | **Ubuntu**            | **Fedora**           |
|----------------------|----------------------|-----------------------|-----------------------|----------------------|
| 8            |8  | 10 (buster)   |  18.04 (bionic) | 所有版本低于 39     |
| 7            | 7 |  9 (stretch)   |  16.04 (xenial) |                      |
 |              | | 8 (jessie)    | 14.04 (trusty) |                      |
 |               | |                      |                       以及以下版本： mantic 、 lunar 、kinetic 、impish、 hirsute 、groovy、eoan 、disco、 cosmic            |                      |

**Comment by zhaojing1987** [comment]
| Distribution         | Version        | Test1        | Test2        | Test3        |
|--------------|----------------|----------------|----------------|----------------|
| Ubuntu               | 24 |   pass            |       pass        |       pass        |
|                      | 22  |    pass           |        pass       |     pass          |
| Debian (Raspbian)    | 12  |  pass             |        pass       |        pass       |
|                      | 11 |  pass             |       pass        |       pass       |
| CentOS               | 8              |   pass            |        pass       |       pass        |
|                      | 7              |   pass            |       pass        |       pass        |
| CentOS Stream        | 9              |   pass      |      pass         |        pass       |
|                                 | 8              | error              |               |               |
| RHEL                 | 9              | pass      |     pass          |       pass       |
|                          | 8              | pass      |        pass       |       pass        |
|                          | 7              | pass(centos仓库)              |       pass        |        pass       |
| Fedora               | 39+            |pass      | pass |      pass        |               |
| Amazon Linux         | 2023           |pass      | pass |        pass       |               |
| Alma Linux           | 9              |pass      |       pass        |       pass        |
|                             | 8              |pass       |       pass        |       pass        |
| Rocky Linux          | 9              |pass      |       pass        |        pass       |
|                              | 8              |pass      |        pass       |       pass        |
| Oracle Linux         | 9              |pass       |       pass        |        pass      |
|                             | 8              |pass       |         pass      |       pass        |
|                             | 7              |               |               |               |

**Comment by zhaojing1987** [comment]
CentOS Stream 8：
![image](https://github.com/user-attachments/assets/f37af469-a41f-48e7-8f18-f8050b20851e)

**Comment by qiaofeng1227** [comment]
2.1.16-rc1测试
开机后ssh登陆：使用下列脚本测试。
```
wget -O install.sh https://websoft9.github.io/websoft9/install/install.sh && bash install.sh --port 9000 --channel dev
```
| Distribution         | Version        | Test1        | 
|--------------|----------------|----------------|
| Ubuntu               | 24 |      pass        |            
|                      | 22  |       pass       |            
| Debian (Raspbian)    | 12  |        pass      |      
|                      | 11 |       pass       |           
| CentOS               | 8              |      pass        |       
|                      | 7              |       cockpit doesn't support menu       |          
| CentOS Stream        | 9              |   pass     |           
|                                 | 8              |              |              
| RHEL                 | 9              |   pass   |          
|                          | 8              |   pass   |        
|                          | 7              |      error(cockpit doesn't support menu)        |            
| Fedora               | 39+            |  pass   | |    
| Amazon Linux         | 2023           |   error(Installation failed)  | |             
| Alma Linux           | 9              | error(Installation failed)    |             
|                             | 8              |  error(Installation failed)    |            
| Rocky Linux          | 9              |  error(Installation failed) |       
|                              | 8              |  error(Installation failed)  |            
| Oracle Linux         | 9              |    error(certificate is not trusted)  |           
|                             | 8              |      |           
|                             | 7              |               |

**Comment by czj69233** [comment]
### Amazon Linux 2023 Error:
```
[root@iZbp13lt7d5tpvgtzb6j5yZ ~]# wget -O install.sh https://websoft9.github.io/websoft9/install/install.sh && bash install.sh --port 9000 --channel dev
--2024-12-04 13:55:51--  https://websoft9.github.io/websoft9/install/install.sh
Resolving websoft9.github.io (websoft9.github.io)... 185.199.109.153, 185.199.110.153, 185.199.108.153, ...
Connecting to websoft9.github.io (websoft9.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15242 (15K) [application/x-sh]
Saving to: ‘install.sh’

100%[=======================================================================================================>] 15,242      57.2KB/s   in 0.3s   

2024-12-04 13:56:05 (57.2 KB/s) - ‘install.sh’ saved [15242/15242]

execute_mode=install

------ Welcome to install Websoft9, it will take 3-5 minutes ------

Your installation parameters are as follows: 
--version: latest
--port: 9000
--channel: dev
--path: /data/websoft9/source
--apps: 
--mirrors: https://dockerhub.websoft9.com
--devto: 

Your OS: 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
Install from url: https://artifact.websoft9.com/dev/websoft9
Directory /data/websoft9/source already exists and installation will cover it.
Stop Websoft9 Proxy and Cockpit service for reserve ports...
docker stop websoft9-proxy not need 
All ports are available

[Tools] -  Starting install necessary tool...
Cannot open: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm. Skipping.
Error: Nothing to do

[Download Source] -  Download Websoft9 source code from https://artifact.websoft9.com/dev/websoft9/websoft9-latest.zip
--2024-12-04 13:56:06--  https://artifact.websoft9.com/dev/websoft9/websoft9-latest.zip
Resolving artifact.websoft9.com (artifact.websoft9.com)... 104.21.38.184, 172.67.137.91, 2606:4700:3032::ac43:895b, ...
Connecting to artifact.websoft9.com (artifact.websoft9.com)|104.21.38.184|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80070 (78K) [application/zip]
Saving to: ‘/tmp/websoft9-latest.zip.3’

100%[=======================================================================================================>] 80,070       165KB/s   in 0.5s   

2024-12-04 13:56:09 (165 KB/s) - ‘/tmp/websoft9-latest.zip.3’ saved [80070/80070]

sudo: unzip: command not found
Failed to unzip source package.

[Backend] -  Install backend docker services
Set Docker for Websoft9 backend service...
firewalld is not running
Failed to restart docker.service: Unit not found.
install.sh: line 403: cd: /data/websoft9/source/docker: No such file or directory
Failed to change directory.


-------- Systemd --------

[Systemd] -  Install Systemd service
cp: cannot stat ‘/data/websoft9/source/systemd/script/*’: No such file or directory
cp: cannot stat ‘/data/websoft9/source/systemd/websoft9.service’: No such file or directory
Failed to copy Systemd service file.
bash: /data/websoft9/source/install/install_cockpit.sh: No such file or directory
bash: /data/websoft9/source/install/install_plugins.sh: No such file or directory
Restart Docker for Firewalld...
Failed to restart docker.service: Unit not found.
Script execution time: 4 seconds

-- Install success! ------
grep: /lib/systemd/system/cockpit.socket: No such file or directory
Access Websoft9 console by: http://Internet IP: and using Linux user for login
```
