### ISSUE TITLE
端口转发后仅能打开面板，无法使用“应用商店”、“容器”、“网关”等功能

### ISSUE THREAD

**Issue by 476663616** [Websoft9/websoft9#552]
由于是校园网，服务器集群采用路由器管理，由路由器配置端口转发来访问不同的服务器。

对于安装了Websoft9的服务器，我们对该服务器的9000端口进行了转发，远程机器可以正常通过转发端口打开面板，但是无法使用里面的组件。

在服务器本地进行了测试，是可以正常使用其中的所有功能，是还需要转发更多的端口吗？

**Comment by chendelin1982** [comment]
目前 Websoft9 依赖 80,9000 两个端口，且 80 端口也需要被转发到外网

**Comment by 476663616** [comment]
收到，已经可以用了，感谢~
