### ISSUE TITLE
upgrade error at CentOS Stream

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#554]
**Describe the bug**

When upgrade  Websoft9, below container failed or not migrated

- [x] - websoft9-proxy: initproxy.conf not migrate
- [x] - websoft9-deployment: always restart
  - [x]  if init.flag(this file not exist at old version)
  - [x]  write password file need after set portainer successfully
- [x] - can not auto login websoft9-git at Websoft9 Console（Clear browse cache）

**Comment by chendelin1982** [comment]
Why Websoft9-Gitea need clear browser cache?

**Comment by qiaofeng1227** [comment]
execute install.sh, It can install websoft9 OK.
Delete containers and volumes and restart websoft9, throws "Network Error" .


![image](https://github.com/user-attachments/assets/e6c3b04d-cd61-445a-b0cf-34e55075717a)


```
root@iZbp107y3zdl9fzq96rgawZ:/data/websoft9/source/docker# docker logs websoft9-proxy
cp: cannot create regular file '/data/nginx/default_host/initproxy.conf': No such file or directory
❯ Configuring npm user ...

```

**Comment by zhaojing1987** [comment]
Portainer 已经修复，从文件判断改为接口判断是否初始化，已提交！

**Comment by zhaojing1987** [comment]
Gitea升级导致 cookie ：i_like_gitea 残留，出现了2个，但是path 不一样，/w9git 和 /w9git/ ；
发现旧版gitea的cookie的path都是/w9git/，中间升级过一次以后是/w9git ；
现在不能登录是由于i_like_gitea 这个cookie冲突，手动删除 path为/w9git/的cookie ：i_like_gitea即可；
尝试在程序中删除，由于这是官方写入的且设置了httponly，导致不能删除；
后面的版本没有此问题！
