### ISSUE TITLE
Output [can't make image infomation] on install_version.txt 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#74]
In order to make the tester more clear whether the current test can be make a image on Cloud.

**Comment by xiangbiao1370147256** [comment]
![image](https://user-images.githubusercontent.com/112335402/187856105-dce9c056-e198-4050-a213-3402d7bb3876.png)   ok
带T测试模式最后上面输出了上面的文字

**Comment by xiangbiao1370147256** [comment]
![image](https://user-images.githubusercontent.com/112335402/187865646-766c2104-edc8-43f9-ab99-d52b0ecb38e3.png)
不带T生产模式最后没有输出上面的文字
