### ISSUE TITLE
FASTPANEL 注意事项

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/websoft9#78]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [x] create instance from private image

#### 修改 Nginx 配置，自动添加服务器内网  IP 
![%ZY_`3X@94`2Z0XL727TRRV](https://user-images.githubusercontent.com/62225175/188814783-5f3f37be-aaba-41cb-a9e1-4928914ff322.png)

#### 启动后，建网站前， 需修改面板 IP, 默认为内网IP ，改成公网 IP,并做映射
![image](https://user-images.githubusercontent.com/62225175/188815116-4560b186-2e04-4c28-8055-882d790e0a16.png)

![image](https://user-images.githubusercontent.com/62225175/188823000-75a562b4-b14d-4f49-a13b-e4ec4064f95f.png)

#### 安装不同版本 PHP
![5HQ05_UBOWM$XIQKMAH7YA3](https://user-images.githubusercontent.com/62225175/188815217-c237b666-3f4b-478c-9665-fd0ab992450d.png)

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
complete
