### ISSUE TITLE
check APP_HTTP_PORT on .env and docker-compose.yml

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#79]
```
1	docker-activemq
2	docker-akeneo
3	docker-alfresco
4	docker-algolia
5	docker-ansible
6	docker-apache
7	docker-apex
8	docker-apisix
9	docker-awx
10	docker-bigbluebutton
11	docker-bt
12	docker-budibase
13	docker-caddy
14	docker-canal
15	docker-cells
16	docker-ckan
17	docker-cloudbeaver
18	docker-cmak
19	docker-codeserver
20	docker-collabora
21	docker-coredns
22	docker-couchdb
23	docker-countly
24	docker-dgraph
25	docker-directus
26	docker-discuz
27	docker-discuzq
28	docker-docusaurus
29	docker-dolibarr
30	docker-drupal
31	docker-elasticsearch
32	docker-elk
33	docker-erpnext
34	docker-espocrm
35	docker-falcon
36	docker-geoserver
37	docker-ghost
38	docker-gitlab
39	docker-gogs
40	docker-grafana
41	docker-graylog
42	docker-guacamole
43	docker-haproxy
44	docker-influxdb
45	docker-jenkins
46	docker-jetty
47	docker-jitsi
48	docker-joomla
49	docker-jumpserver
50	docker-jupyterhub
51	docker-kafka
52	docker-kibana
53	docker-knowage
54	docker-kodcloud
55	docker-kong
56	docker-logstash
57	docker-magento
58	docker-mariadb
59	docker-mattermost
60	docker-mautic
61	docker-mediawiki
62	docker-memadmin
63	docker-memcached
64	docker-metabase
65	docker-mingdao
66	docker-minio
67	docker-mongocompass
68	docker-mongodb
69	docker-mongoexpress
70	docker-moodle
71	docker-mysql
72	docker-neo4j
73	docker-netdata
74	docker-nextcloud
75	docker-nextterminal
76	docker-nginx
77	docker-nginxproxymanager
78	docker-nocodb
79	docker-nopcommerce
80	docker-odoo
81	docker-officesuite
82	docker-onlyoffice
83	docker-onlyofficedocs
84	docker-opencart
85	docker-opencv
86	docker-opensearch
87	docker-oracle
88	docker-owncloud
89	docker-pgadmin
90	docker-phpmyadmin
91	docker-pimcore
92	docker-portainer
93	docker-postgresql
94	docker-prestashop
95	docker-projector
96	docker-prometheus
97	docker-rabbitmq
98	docker-rancher
99	docker-redash
100	docker-redis
101	docker-redisinsight
102	docker-redmine
103	docker-rethinkdb
104	docker-rocketchat
105	docker-runtime
106	docker-sakai
107	docker-saleor
108	docker-scratch
109	docker-seafile
110	docker-sqlserver
111	docker-squid
112	docker-sscms
113	docker-strapi
114	docker-suitecrm
115	docker-superset
116	docker-template
117	docker-tensorflow
118	docker-theia
119	docker-tinyproxy
120	docker-tomcat
121	docker-traefik
122	docker-typesense
123	docker-typo3
124	docker-umbraco
125	docker-varnish
126	docker-vault
127	docker-visualstudio
128	docker-vtiger
129	docker-webmin
130	docker-wordpress
131	docker-xwiki
132	docker-zabbix
133	docker-zammad
134	docker-zentao

```

**Comment by qiaofeng1227** [comment]
1. 检查.env 文件是否有APP_PORT，如果有需要修改成APP_HTTP_PORT
2. 并将docker-compose.yml中所有的APP_PORT（可能有多个）也改成APP_HTTP_PORT

**Comment by xiangbiao1370147256** [comment]
![{56P45LHC 3@JNS@T6H6Z9P](https://user-images.githubusercontent.com/112335402/189253337-052c2d8b-6bf3-4ae5-a6be-f48075a168c4.png)
![IH0HCVE15@2E@FZQR9Q5DMD](https://user-images.githubusercontent.com/112335402/189253409-41936f4c-3312-4b5a-b5f2-529d907fb0da.png)
![LU2WDN%BS%YUFD@LY7QSLJI](https://user-images.githubusercontent.com/112335402/189253410-72e32eb9-bd95-425a-b024-f4178fbf7c45.png)
![24@09JGU{H%{`4R{{Z9BO0T](https://user-images.githubusercontent.com/112335402/189253415-4ee7f010-2222-4f81-b679-0005f5a7ba50.png)
![(WTX591BPXW Y(}35}7}(TV](https://user-images.githubusercontent.com/112335402/189253422-9a4ee0bb-4a4c-43db-848e-4d6fa90690c3.png)
![5 $L2B9R%6C{0S{6(C 4HDK](https://user-images.githubusercontent.com/112335402/189253427-3e8ca8cf-7de2-443e-8b90-2919e636ca17.png)
![UN{V(4 { 5)SQ~`}W2_U 3E](https://user-images.githubusercontent.com/112335402/189253430-2f59e5d6-2a41-4385-8278-419e98833424.png)


![U17JEX6P%SWML59GIUZ(J1B](https://user-images.githubusercontent.com/112335402/189253435-3ce407fe-eb9b-463a-b3a7-686ac0c57175.png)
![({F(7{U$ZXUYAPO~QF~VZJ6](https://user-images.github
![B8U6KM1HB1))NG6G HV~{$0](https://user-images.githubusercontent.com/112335402/189253451-27cdec82-5136-4214-8e2f-93fd6951a3c9.png)
usercontent.com/112335402/189253442-2a5fb70c-8b48-4089-85e2-e18f483c1c6b.png)
![K)TY8B%((4_)LE ~6%5RS8](https://user-images.githubusercontent.com/112335402/189253463-246050cc-cbad-405a-8fbf-86356b955c2f.png)
![V V$V8DRYB3P%RZ)ZLLZ 4A](https://user-images.githubusercontent.com/112335402/189253474-4b0f4616-6e87-4b01-a222-5c8dfdde2bf2.png)
![D`Y{8Y$PY}(G`Z%JN%BO Z0](https://user-images.githubusercontent.com/112335402/189253487-9efe918a-d6f2-4f0d-983d-eec51e2bfa9c.png)

![J)U$IZXB(L {2IP}0_6GS`A](https://user-images.githubusercontent.com/112335402/189253503-f69ed18a-f12c-425b-ace0-a8196b9d3558.png)

![2WC3MO}1TJO@`L@CX}}~ `V](https://user-images.githubusercontent.com/112335402/189253494-59a79510-a4a8-4b95-8b98-fb47a75202fc.png)
![3Z5%0YDEB2A$95E~ 5_X1XV](https://user-images.githubusercontent.com/112335402/189253520-91750f74-15c0-4d9d-9784-30f63db4b80f.png)
![{%6MR@ZW4`)1978L`E90 HJ](https://user-images.githubusercontent.com/112335402/189253529-f3bd294c-5ab7-4522-8668-c2ae7a627cde.png)

![09H2H0XI0JT59`WWDD0Y8(C](https://user-images.githubusercontent.com/112335402/189253535-db1ec069-4ef8-4f07-a4a5-5a5e1b3593fb.png)

**Comment by qiaofeng1227** [comment]
修改样式:
APP_URL_REPLACE=true
APP_URL=appname.example.com
APP_URL=appname.example.com:$APP_HTTP_PORT

**Comment by xiangbiao1370147256** [comment]
ok

**Comment by xiangbiao1370147256** [comment]
1.alfresco    ok
2.cells         ok
3.codeserver        ok
4.ghost        ok
5.gitlab        ok
6.magento      ok
7.mattermost       ok
8.mediawiki        ok
9.owncloud      ok
10.prestashop       ok
11.seafile          ok
12.template        ok
