### ISSUE TITLE
Ubuntu 22.04 操作系统 测试

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#90]
使用mcloud分别在 以下云测试ubuntu22.04操作系统是否能开机
- 阿里云
- 腾讯云
- AWS
- Azure

测试方法：
1. ssh 登陆服务器，有些云平台会提示操作系统，如：Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-125-generic x86_64)
2. 命令查看
```
➜  ~  cat /proc/version
Linux version 5.4.0-125-generic (buildd@lcy02-amd64-083) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022


➜  ~ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

```

**Comment by xiangbiao1370147256** [comment]
1.阿里云
![image](https://user-images.githubusercontent.com/112335402/194789930-9073ca23-5765-4fdf-8c66-2fed872f3801.png)
2.腾讯云
![image](https://user-images.githubusercontent.com/112335402/194790560-fe51911a-ce2e-4e8c-98c9-d6db838d66c3.png)
3.亚马逊
![image](https://user-images.githubusercontent.com/112335402/194791415-bfd0e1ba-e981-4f55-b439-c6df7ec45c36.png)
4.微软
![image](https://user-images.githubusercontent.com/112335402/194791473-799639b5-ae0c-4ab0-b3f4-38076081fb1b.png)

**Comment by qiaofeng1227** [comment]
OK
