### ISSUE TITLE
Azure 漏洞对应

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#91]
预对应镜像列表：

可系统化测试
-  cloudbeaver xxx  on centos7.9 
-  mysql 5.5,5.6,8.0  on centos 7.9

需要修改文档：
-  dolibarr xxx on centos7.9 ok
-  grafana xxx on centos7.9 ok
-  jenkins on centos7.9 ok
-  mattermost  on centos7.9 bug
-  zabbix on centos7.9 bug
-  zentao on centos7.9 ok
-  owncloud centos7.9 bug
-  nextcloud centos7.9 ok
-  postgresql 11 centos7.9 ok
-  rabbitmq centos7.9
-  suitecrm centos7.9 ok
-  redis 3.0,3.2,5,6 on  centos 7.9 ok

需要研发产品：
-  lamp/lemp 一共8个镜像
-  node系列 一共11个镜像
-  openjdk1.8-tomcat8 on centos7.9
-  openjdk11-tomcat8 on centos7.9
-  openjdk11-tomcat9 on centos7.9

**Comment by morning-tan** [comment]
https://drive.weixin.qq.com/s?k=AEYAzAcRAA4NMSXlIw

**Comment by qiaofeng1227** [comment]
已经对应完毕
