### ISSUE TITLE
ssh 和winscp 连接ubuntu22.04

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/websoft9#93]
阿里云带T测mysql5.5-ubuntu22.04，使用公钥无法连接服务器，winscp提示如下：
![image](https://user-images.githubusercontent.com/54173243/194981071-86ab6905-5b28-4562-bf5b-7f8f2ee71ed2.png)

同时IP地址可访问

**Comment by qiaofeng1227** [comment]
ssh 私钥太旧，下列命令生成即可（xshell，winscp在centos7.9 ubuntu22.04,20.04都验证过）
```
ssh-keygen -t ecdsa -b 521
```

**Comment by qiaofeng1227** [comment]
新的算法，腾讯，AWS不支持。升级winscp和xshell客户端。
